const userGuess = document.getElementById("user-guess");

const usersWord = document.getElementById("scrambled-word");
const levelOutput = document.getElementById("level");
const scoreOutput = document.getElementById("score");
const attemptsOutput = document.getElementById("attempts");
const gameContainer = document.getElementById("game-container");
const guessContainer = document.getElementById("guess-container");
const rules = document.getElementById("rules");
const playBtn = document.getElementById("play-btn");

let level = 1;
let score = 0;
let word;
let attempts = 0;
let correct = 0;


function gameover(){
cancelInterval(timer);
$('#playAgainButton,).show();
}
function updateTimer(){
timeleft =timeleft-1;
if(timeLeft>=0)
$('#timer').html(timeLeft);
else{
gameOver();
}
}
function start()
{
timer=setInterval(updateTimer,1000);
updateTimer();
$('#playAgainButton').hide();
}

const lvlOneWords = [
  "aim",
  "bed",
  "bee",
  "buy",
  "can",
  "cow",
  "did",
  "die",
  "dry",
  "egg",
  "fat",
  "fix",
  "few",
  "gym",
  "guy",
  "hen",
  "hut",
  "ill",
  "ice",
  "ink",
  "jet",
  "job",
  "kid",
  "lip",
  "leg",
  "let",
  "law",
  "mat",
  "mid",
  "now",
  "oil",
  "owl",
  "off",
  "one",
  "pen",
  "shy",
  "the",
  "try",
  "van",
  "yak",
  "you",
  "zip"
];

const lvlTwoWords = [
  "acid",
  "also",
  "arcs",
  "area",
  "baby",
  "back",
  "ball",
  "bell",
  "book",
  "cabs",
  "chef",
  "chat",
  "chin",
  "dash",
  "dark",
  "deep",
  "dice",
  "easy",
  "ends",
  "exam",
  "face",
  "fact",
  "fair",
  "fall",
  "farm",
  "gain",
  "gets",
  "glad",
  "hats",
  "help",
  "head",
  "kept",
  "keys",
  "less",
  "mark",
  "mile",
  "name",
  "pack",
  "self",
  "slip",
  "thin",
  "tied",
  "tree",
  "ugly",
  "used",
  "visa",
  "wait",
  "zero",
  "zinc",
  "zips",
  "zone"
];

const lvlThreeWords = [
  "about",
  "above",
  "array",
  "angry",
  "basic",
  "below",
  "cable",
  "crack",
  "cycle",
  "daddy",
  "dance",
  "digit",
  "earth",
  "event",
  "exact",
  "equal",
  "false",
  "fever",
  "fiber",
  "fifty",
  "fruit",
  "gamma",
  "gangs",
  "gawks",
  "gecko",
  "goofy",
  "goner",
  "guild",
  "hairy",
  "harem",
  "hedge",
  "hello",
  "helms",
  "honor",
  "image",
  "imply",
  "itchy",
  "issue",
  "ionic",
  "jacks",
  "japan",
  "jewel",
  "juice",
  "junky",
  "keeps",
  "kooky",
  "laced",
  "laces",
  "lamps",
  "laser",
  "leaky",
  "lynch",
  "mages",
  "mafia",
  "miles",
  "meats",
  "might",
  "mixer",
  "moths",
  "movie",
  "mushy",
  "named",
  "naval",
  "nears",
  "neigh",
  "newer",
  "nexus",
  "noise",
  "nooks",
  "north",
  "nutty",
  "ogres",
  "olive",
  "olive",
  "opens",
  "oxide",
  "owner",
  "paced",
  "palms",
  "pends",
  "pesky",
  "peppy",
  "petty",
  "phone",
  "phase",
  "porky",
  "pound",
  "pride",
  "print",
  "purse",
  "quack",
  "queen",
  "quart",
  "query",
  "quiet",
  "rafts",
  "rated",
  "react",
  "ready",
  "realm",
  "riced",
  "rides",
  "rigid",
  "rumor",
  "sadly",
  "safes",
  "saggy",
  "sails",
  "saint",
  "salsa",
  "sauce",
  "scone",
  "seeds",
  "scums",
  "sense",
  "shark",
  "sheds",
  "shout",
  "shove",
  "sides",
  "sixth",
  "skeet",
  "skill",
  "snots",
  "solid",
  "sound",
  "south",
  "spoil",
  "stall",
  "stole",
  "store",
  "sulks",
  "swamp",
  "sword",
  "syncs",
  "tempt",
  "texts",
  "texas",
  "today",
  "tonic",
  "topaz",
  "tried",
  "truth",
  "twigs",
  "typos",
  "udder",
  "unify",
  "using",
  "usual",
  "valid",
  "vapor",
  "venue",
  "vowel",
  "waked",
  "waist",
  "waxed",
  "whips",
  "whole",
  "wordy",
  "wreck",
  "yager",
  "yacht",
  "xenon",
  "yield",
  "yikes",
  "zincs",
  "zesty",
  "zones",
  "zincs",
  "zooms",
  "zeros",
  "yummy",
  "youth",
  "yogas",
];

const lvlFourWords = [
  "aboard",
  "abduct",
  "active",
  "acutes",
  "adored",
  "aglets",
  "alaska",
  "alibis",
  "anonym",
  "arches",
  "awhile",
  "awoken",
  "babble",
  "badges",
  "bagels",
  "badman",
  "barbie",
  "bedbug",
  "before",
  "bigots",
  "boiler",
  "bomber",
  "brooms",
  "bureau",
  "burrow",
  "bylaws",
  "cabins",
  "cactus",
  "caddie",
  "caesar",
  "carpet",
  "carved",
  "center",
  "chasms",
  "chewed",
  "chorus",
  "circus",
  "clanky",
  "cocked",
  "condom",
  "corpse",
  "cosmic",
  "credit",
  "crimes",
  "cuffed",
  "cussed",
  "dammit",
  "darker",
  "debits",
  "decent",
  "debris",
  "defuze",
  "detest",
  "dimmer",
  "dissed",
  "donate",
  "dramas",
  "drifts",
  "earths",
  "echoes",
  "elicit",
  "eleven",
  "envoys",
  "enzyms",
  "estate",
  "faceup",
  "fables",
  "failed",
  "factor",
  "falcon",
  "famine",
  "fandom",
  "fecial",
  "feline",
  "fences",
  "fester",
  "finger",
  "fishes",
  "floppy",
  "frauds",
  "frosty",
  "gallon",
  "gambit",
  "garden",
  "gawker",
  "genres",
  "ghostly",
  "gifted",
  "glossy",
  "goodie",
  "grayed",
];

const lvlFiveWords = [
  "abducts",
  "abolish",
  "account",
  "acronym",
  "adjures",
  "adopted",
  "agitate",
  "aidless",
  "alarmed",
  "alchohol",
  "alfredo",
  "alleged",
  "allergy",
  "allures",
  "amiable",
  "aminity",
  "analyst",
  "another",
  "anxious",
  "apricot",
  "arrived",
  "attacks",
  "autopsy",
  "awkward",
  "babbles",
  "backset",
  "banjoes",
  "bandits",
  "batched",
  "beacons",
  "bedpost",
  "bedsore",
  "belongs",
  "benches",
  "berserk",
  "bicolor",
  "bizarre",
  "blubbed",
  "bombers",
  "borrows",
  "bracers",
  "bricked",
  "brutish",
  "bulgers",
  "burrito",
  "bygones",
  "cabinet",
  "cahoots",
  "cameras",
  "canteen",
  "captive",
  "cartels",
  "cashbox",
  "cattish",
  "censors",
  "chaffer",
  "charter",
  "cheeses",
  "chromic",
  "clamped",
  "clunker",
  "collars",
  "compute",
  "consult",
  "corrupt",
  "creamed",
  "crystal",
  "cyclone",
  "daggers",
  "dangled",
  "daycare",
  "decoyed",
  "deduced",
  "dentist",
  "dilator",
  "discard",
  "dollars",
  "doweled",
  "drudged",
  "dwarves",
  "egoless",
  "elastic",
  "endurer",
  "enforce",
  "epilogs",
  "erupted",
  "evoking",
  "extinct",
  "fanatic",
  "ferrets",
  "fifteen",
  "flashes",
  "flushes",
  "footman",
  "fossils",
  "freedom",
  "frowned",
  "furrows",
  "gassers",
  "genders",
  "glimpse",
  "googled",
  "grayest",
  "grudged",
  "gymnast",
  "hagfish",
  "hammock",
  "hardily",
  "healthy",
  "herself",
  "hoarser",
  "hoisted",
  "horsing",
  "hunches",
  "icefall",
  "idolism",
  "illegal",
  "impeach",
  "implode",
  "indoors",
  "inkpots",
  "invades",
  "issuers",
  "jackets",
  "jaywalk",
  "kettles",
  "labeled",
  "mangled",
  "maximum",
  "nibbled"
];

const lvlSixWords = [
  "absolute",
  "adducted",
  "adhering",
  "analyzer",
  "antihero",
  "approved",
  "atonable",
  "babbling",
  "backpack",
  "balloons",
  "baptised",
  "barstool",
  "battiest",
  "bearskin",
  "beefcake",
  "beholder",
  "benefits",
  "bigfoots",
  "birdcage",
  "blasters",
  "bondsman",
  "breeched",
  "budworms",
  "buzzword",
  "cackling",
  "calciums",
  "callback",
  "capacity",
  "carjacks",
  "cartoons",
  "cementery",
  "censuses",
  "cerebal",
  "checkoff",
  "chewable",
  "chubbier",
  "churning",
  "cinnamon",
  "cloggers",
  "cocktail",
  "cogwheel",
  "collapse",
  "concaved",
  "corniest",
  "cowardly",
  "cropland",
  "cynicism",
  "darkness",
  "deadlift",
  "decorate",
  "defusing",
  "deposits",
  "detecter",
  "diasters",
  "dingdong",
  "discrete",
  "doorknob",
  "dreaming",
  "dyslexia",
  "eclipses",
  "employee",
  "enjoyers",
  "enthrall",
  "epilogue",
  "euphoria",
  "expected",
  "facility",
  "fantasia",
  "fawnlike",
  "feminist",
  "flamingo",
  "flowered",
  "fluorite",
  "folklore",
  "forested",
  "friendly",
  "funerals",
  "fuzziest",
  "galivant",
  "germiest",
  "gryphons",
  "haircuts",
  "hammocks",
  "haunting",
  "helmless",
  "hippiest",
  "hotlinks",
  "hysteric",
  "igniters",
  "implored",
  "insanity",
  "isolated",
  "jackpots",
  "journals",
  "kamikaze",
  "kinglike",
  "laborers",
  "landline",
  "laughter",
  "liftoffs",
  "locknuts",
  "luggages",
  "lynchers",
  "machetes",
  "mafiosos",
  "makeover",
  "markdown",
  "material",
  "mermaids",
  "midwifes",
  "ministers",
  "mislodge",
  "modifies",
  "moreover",
  "mulligan",
  "narrowed",
  "neatness",
  "nitrogen",
  "nuthouse",
  "offtrack",
  "ornament",
  "outcasts",
  "outranks",
  "owlishly",
  "pageboys",
  "pardoned",
  "pensions",
  "physical",
  "poaching",
  "promised",
  "quackier",
  "quibbler",
  "quotable",
  "rebounds",
  "refunded",
  "rustable",
  "sailorly",
  "sanitize",
  "scissors",
  "seagulls",
  "selloffs",
  "shavings",
  "shrimper",
  "slowdown",
  "soaplike",
  "syndrome",
  "tailwind",
  "tamponed",
  "thickish",
  "timeouts",
  "township",
  "triplets",
  "uglifier",
  "unbathed",
  "unearths",
  "unkingly",
  "upstarts",
  "vamooses",
  "vehicles",
  "vestless",
  "vomiting",
  "vouchers",
  "warnings",
  "washbowl",
  "welcomer",
  "woefully",
  "xeroxing",
  "yardwork",
  "yearbook",
  "yummiest",
  "zizzling",
  "zoologic",
  "zucchini",
  "zoneless",
  "zonetime",
  "zigzaggy",
  "zillions",
  "zippiest",
  "zappiest",
  "zippered"
];

const lvlSevenWords = [
  "aardvarks",
  "abridging",
  "aftermath",
  "allowance",
  "animalize",
  "apostates",
  "armorless",
  "autograph",
  "babyproof",
  "bagginess",
  "ballerina",
  "banishing",
  "barbecues",
  "beastings",
  "beefcakes",
  "beworried",
  "blackbird",
  "blueberry",
  "bracketed",
  "bullweeds",
  "cancelers",
  "carbuncle",
  "carousels",
  "charmless",
  "collision",
  "communion",
  "corruptor",
  "currently",
  "deafening",
  "declassed",
  "defuelled",
  "descended",
  "dialoging",
  "dimension",
  "distorter",
  "driveways",
  "dyslexias",
  "embezzled",
  "endpoints",
  "equaliser",
  "eventless",
  "explicits",
  "faintness",
  "fiberless",
  "flounders",
  "foreheads",
  "furiously",
  "gemstones",
  "glowingly",
  "grumbling",
  "handbells",
  "heelpiece",
  "hipiness",
  "hookworms",
  "icemakers",
  "impassion",
  "injectors",
  "invasions",
  "jellifies",
  "junctions",
  "kamikazes",
  "kidnapper",
  "kowtowing",
  "labourers",
  "labyrnith",
  "lathering",
  "leveraged",
  "localized",
  "mailrooms",
  "masterful",
  "mentalist",
  "miniskirt",
  "nailbrush",
  "narcistic",
  "nevermore",
  "noncareer",
  "noxiously",
  "obviously",
  "oppressor",
  "outgazing",
  "outwished",
  "overweigh",
  "paintwork",
  "parallels",
  "pedophile",
  "picketers",
  "playbacks",
  "positives",
  "psychotic",
  "qualified",
  "quotation",
  "radiators",
  "ravishing",
  "recognize",
  "remodeler",
  "sasquatch",
  "scavenger",
  "semifinal",
  "shackling",
  "showiness",
  "skullcaps",
  "stampeded",
  "stomached",
  "suiciding",
  "tantalise",
  "technical",
  "testicles",
  "timesaver",
  "usability",
  "viewpoint"
];

const lvlEightWords = [
  "acetylates",
  "bamboozles",
  "beekeepers",
  "calendared",
  "centipedes",
  "chimpanzee",
  "debilitate",
  "deportment",
  "devolution",
  "eccentrics",
  "encapsules",
  "exaggerate",
  "federalize",
  "flabbiness",
  "frequently",
  "ghoulishly",
  "graciously",
  "handmaiden",
  "hauntingly",
  "hypnotized",
  "immobilize",
  "imperfects",
  "intoxicate",
  "jackknifes",
  "kidnapping",
  "laundering",
  "liquidated",
  "manslayers",
  "meanderers",
  "misbehaves",
  "necromancy",
  "obediences",
  "palindrome",
  "perfecters",
  "puzzlingly",
  "quantities",
  "rearousing",
  "redevelops",
  "reputation",
  "scandalize",
  "seductions",
  "slumberers",
  "temporally",
  "ultraclean",
  "undefeated",
  "vigorously",
  "watermarks",
  "wristbands",
  "yellowtail",
  "zoologists"
];

function reset() {
  level = 1;
  score = 0;
  correct = 0;
  attempts = 0;
  word = "";
  updateBoard();
  info.innerHTML = "";
  userGuess.value = "";
}

function randomWord(lvl) {
  word = lvl[Math.floor(Math.random() * lvl.length + 1) - 1];
  return word;
}

function scrambleWord(word) {
  let letters = word.split("");
  let currentIndex = letters.length,
    temporaryValue,
    randomIndex;

  // While there remain elements to shuffle...
  while (0 !== currentIndex) {
    // Pick a remaining element...
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;

    // And swap it with the current element.
    temporaryValue = letters[currentIndex];
    letters[currentIndex] = letters[randomIndex];
    letters[randomIndex] = temporaryValue;
  }

  return letters.join(" ");
}
function updateBoard() {
  scoreOutput.innerHTML = score;
  levelOutput.innerHTML = level;
  attemptsOutput.innerHTML = attempts;
}

function checkAnswer(guess) {
  console.log(`Correct: ${correct}`);
  if (correct == 3) {
    level += 1;
    correct = 0;
  }

  if (attempts == 3) {
    guessContainer.classList.toggle("hidden");
    info.innerHTML =
      "<p class='retry'>Sorry. You are out of chances. <button id='retry-button'>Retry</button> </p>";
    reset();
  }

  if (guess === word) {
    info.innerHTML = "<span class='correct'>CORRECT</span>";
    score += 1;
    correct += 1;
    attempts = 0;
    setLevel();
  } else {
    info.innerHTML = "<span class='incorrect'>Bzzzt! That's not right!</span>";
    score -= 1;
    attempts += 1;
  }

  updateBoard();
}

function setLevel() {
  if (level == 1) {
    randomWord(lvlOneWords);
  } else if (level == 2) {
    randomWord(lvlTwoWords);
  } else if (level == 3) {
    randomWord(lvlThreeWords);
  } else if (level == 4) {
    randomWord(lvlFourWords);
  } else if (level == 5) {
    randomWord(lvlFiveWords);
  } else if (level == 6) {
    randomWord(lvlSixWords);
  } else if (level == 7) {
    randomWord(lvlSevenWords);
  } else if (level == 8) {
    randomWord(lvlEightWords);
  } else if (level == 9) {
    info.innerHTML =
      "<span class='win'>You Win! Great job! </br> You can reset or keep playing.</span>";
  }

  console.log(`Word: ${word}`);
  usersWord.innerHTML = scrambleWord(word);
}

playBtn.addEventListener("click", function(e) {
  rules.classList.toggle("hidden");
  gameContainer.classList.remove("hidden");
});


setLevel();
